// Generated by CoffeeScript 1.10.0
var Slack, autoMark, autoReconnect, models, slack, token;

Slack = require('slack-client');

models = require('./models');

token = 'xoxb-12902597654-5iHlSdLENvmqdDAdhfzR7tC2';

autoReconnect = true;

autoMark = true;

slack = new Slack(token, autoReconnect, autoMark);

slack.on('open', function() {
  var channel, channels, group, groups, id, messages, unreads;
  channels = [];
  groups = [];
  unreads = slack.getUnreadCount();
  channels = (function() {
    var ref, results;
    ref = slack.channels;
    results = [];
    for (id in ref) {
      channel = ref[id];
      if (channel.is_member) {
        results.push("#" + channel.name);
      }
    }
    return results;
  })();
  groups = (function() {
    var ref, results;
    ref = slack.groups;
    results = [];
    for (id in ref) {
      group = ref[id];
      if (group.is_open && !group.is_archived) {
        results.push(group.name);
      }
    }
    return results;
  })();
  console.log("Welcome to Slack. You are @" + slack.self.name + " of " + slack.team.name);
  console.log('You are in: ' + channels.join(', '));
  console.log('As well as: ' + groups.join(', '));
  messages = unreads === 1 ? 'message' : 'messages';
  return console.log("You have " + unreads + " unread " + messages);
});

slack.on('message', function(message) {
  var can_record, channel, channelError, channelName, errors, help, record, response, send, should_help, should_record, should_respond, text, textError, ts, type, typeError, user, userName;
  channel = slack.getChannelGroupOrDMByID(message.channel);
  user = slack.getUserByID(message.user);
  response = '';
  type = message.type, ts = message.ts, text = message.text;
  channelName = (channel != null ? channel.is_channel : void 0) ? '#' : '';
  channelName = channelName + (channel ? channel.name : 'UNKNOWN_CHANNEL');
  userName = (user != null ? user.name : void 0) != null ? "@" + user.name : "UNKNOWN_USER";
  console.log("Received: " + type + " " + channelName + " " + userName + " " + ts + " \"" + text + "\"");
  if (type === 'message' && (text != null) && (channel != null)) {
    should_respond = function(text) {
      return /benbot/i.test(text);
    };
    should_record = function(text) {
      return /record/i.test(text);
    };
    can_record = function(text) {
      var count, matches;
      matches = text.match(/\"|\”|\“/g);
      count = matches ? matches.length : 0;
      if (count !== 2) {
        return false;
      } else {
        return true;
      }
    };
    should_help = function(text) {
      return /help/i.test(text);
    };
    record = function(text) {
      var quote;
      quote = text.match(/(\"|\“)(.*)(\"|\”)/i);
      console.log(quote);
      models.record(quote[0].slice(1, -1));
      return channel.send("Thanks, I'm going to start saying: " + quote[0]);
    };
    help = function() {
      return channel.send("I know how to: \'record \"things in quotes\"\''. Otherwise I just say pick-nitty things.");
    };
    send = function(quotes) {
      var quote;
      console.log(quotes);
      text = [
        (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = quotes.length; i < len; i++) {
            quote = quotes[i];
            results.push(quote);
          }
          return results;
        })()
      ].join(" \n");
      channel.send(text);
      return console.log("@" + slack.self.name + " responded with \"" + text + "\"");
    };
    if (should_respond(text)) {
      if (should_record(text)) {
        if (can_record(text)) {
          return record(text);
        } else {
          return channel.send('Sorry, could you say that again with two quotes "(example)"?');
        }
      } else if (should_help(text)) {
        return help();
      } else {
        return models.quote(send);
      }
    }
  } else {
    typeError = type !== 'message' ? "unexpected type " + type + "." : null;
    textError = text == null ? 'text was undefined.' : null;
    channelError = channel == null ? 'channel was undefined.' : null;
    errors = [typeError, textError, channelError].filter(function(element) {
      return element !== null;
    }).join(' ');
    return console.log("@" + slack.self.name + " could not respond. " + errors);
  }
});

slack.on('error', function(error) {
  return console.error("Error: " + error);
});

slack.login();
