// Generated by CoffeeScript 1.10.0
var client, connectionString, loadData, pg, query, quotes;

pg = require('pg');

quotes = [];

connectionString = 'postgres://localhost:5432/benbot';

console.log(connectionString);

client = new pg.Client(connectionString);

client.connect();

query = client.query('CREATE TABLE quotes(id SERIAL PRIMARY KEY, text VARCHAR(255) not null, date_last_quoted TIMESTAMP)');

console.log('createdb benbot');

query.on('end', function(result) {
  console.log('query end');
  return loadData();
});

loadData = function() {
  var data, readline, rl;
  readline = require('linebyline');
  data = 'data.txt';
  rl = readline(data);
  rl.on('line', function(line) {
    console.log('Line from file:', line);
    return quotes.push(line);
  });
  return rl.on('close', function() {
    query;
    var i, len, quote;
    for (i = 0, len = quotes.length; i < len; i++) {
      quote = quotes[i];
      query = client.query("INSERT INTO quotes(text) values($1)", [quote]);
      console.log('insert', query.text);
    }
    query.on('end', function() {
      console.log('query end');
      return client.end();
    });
    return query.on('error', function(error) {
      return console.log(error);
    });
  });
};
