// Generated by CoffeeScript 1.10.0
var Models, connectionString, pg;

pg = require('pg');

connectionString = 'postgres://localhost:5432/benbot';

Models = function() {};

Models.prototype.record = function(quote) {
  var data;
  data = {
    quote: quote
  };
  return pg.connect(connectionString, function(err, client, done) {
    var query;
    if (err) {
      done();
      console.log(err);
      return {};
    }
    client.query("INSERT INTO quotes(text) values($1)", [data.quote]);
    query = client.query("SELECT * FROM quotes ORDER BY id ASC");
    query.on('row', function(row, result) {
      return result.addRow(row);
    });
    return query.on('end', function(result) {
      done();
      return result;
    });
  });
};

Models.prototype.quote = function(send) {
  return pg.connect(connectionString, function(err, client, done) {
    var query;
    if (err) {
      done();
      console.log(err);
      return {};
    }
    query = client.query("SELECT * FROM quotes ORDER BY date_last_quoted ASC NULLS FIRST LIMIT 1;");
    query.on('row', function(row, result) {
      var update;
      result.addRow(row.text);
      update = client.query("UPDATE quotes SET date_last_quoted = current_timestamp WHERE id = " + row.id + ";");
      return update.on('end', function(result) {
        return done();
      });
    });
    return query.on('end', function(result) {
      done();
      return send([result.rows[0]]);
    });
  });
};

module.exports = new Models();
